version: "3.7"
services:
  influxdb:
    image: influxdb:1.7-alpine
    container_name: smaga_influxdb

  telegraf:
    image: telegraf:1.10-alpine
    container_name: smaga_telegraf
    volumes:
      - './telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:6.2.2
    container_name: smaga_grafana
    volumes:
      - './grafana.ini:/usr/share/grafana/conf/defaults.ini:ro'
      - 'grafana_data:/var/lib/grafana'
    depends_on:
      - influxdb

  nginx:
    image: nginx:1.17-alpine
    container_name: smaga_nginx
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '127.0.0.1:8888:80'
    depends_on:
      - telegraf
      - grafana

volumes:
  grafana_data: